

BASE = "https://api.reelgood.com"

SERVICES = {
    "philo": "Philo",
    "netflix": "Netflix",
    "netflix_basic": "Netflix (Basic)",
    "peacock": "Peacock",
    "hbo_max": "HBM Max",
    "apple_tv_plus": "Apple TV+",
    "disney_plus": "Disney+",
    "amazon_buy": "Amazon Rent/Buy",
    "amazon_prime": "Amazon Prime",
    "hbo": "HBO",
    "hulu_plus": "Hulu+",
    "paramount_plus": "Paramount+",
    "fubo_tv": "Fubo TV",
    "tubi_tv": "Tubi TV",
    "plutotv": "PlutoTV",
    "plex_free": "Plex Free",
    "vudu_free": "Vudu Free",
    "crackle": "Crackle",
    "imdb_tv": "IMDB TV",
    "peacock_free": "Peacock Free",
    "bet_plus": "Bet+",
    "directv": "DirecTV",
    "kanopy": "Kanopy",
    "fandor": "Fandor",
    "fx_tveverywhere": "FX TVeverywhere",
    "epix": "Epix",
    "popcornflix": "Popcorn Flix",
    "starz": "Starz",
    "mubi": "Mubi",
    "hoopla": "Hoopla",
    "shudder": "Shudder",
    "criterion_channel": "Criterion Channel",
    "tbs": "TBS",
    "tnt": "TNT",
    "trutv_tveverywhere": "TruTV TVeverywhere",
    "tvision": "TVision",
    "amc": "AMC",
    "hallmark_movies_now": "Hallmark Movies Now",
    "showtime": "Showtime",
    "discovery_plus": "Discovery+",
    "nbc_tveverywhere": "Nbc TVeverywhere",
    "hallmark_everywhere": "Hallmark Everywhere",
    "cinemax": "Cinemax",
    "youtube_premium": "Youtube Premium",
    "lifetime_tveverywhere": "Lifetime TVeverywhere",
    "syfy_tveverywhere": "Syfy TVeverywhere",
    "vh1_tveverywhere": "Vh1 TVeverywhere",
    "natgeo_tveverywhere": "NatGeo TVeverywhere",
    "crunchyroll_premium": "Crunchyroll Premium",
    "crunchyroll_free": "Crunchyroll Free",
    "britbox": "Britbox",
    "watch_tcm": "Watch TCM",
    "funimation": "Funimation",
    "cartoon_network": "Cartoon Network",
    "comedycentral_tveverywhere": "Comedycentral TVeverywhere",
    "disneynow": "DisneyNow",
    "amc_premiere": "AMC Premiere",
    "abc_tveverywhere": "ABC TVeverywhere",
    "ae_tveverywhere": "AE TVeverywhere",
    "acorntv": "Acorntv",
    "sundance_tveverywhere": "Sundance TVeverywhere",
    "bet_tveverywhere": "Bet TVeverywhere",
    "bbc_america_tve": "BBC America TVe",
    "dc_universe": "DC Universe",
    "indieflix": "Indieflix",
    "ifc": "IFC",
}





